#!/usr/bin/env python

# This tool allows the user to interact with spotinst API
# run the script with the -h flag for help

from json import loads, dumps
from collections import OrderedDict
from optparse import OptionParser
from os import system, environ
from sys import argv, stdout
from os import path
from base64 import b64encode, b64decode
from commands import getoutput, getstatusoutput
from threading import Thread
from pkg_resources import DistributionNotFound


# This function opens a thread with args
def open_thread(thread_target,thread_args):
    t = Thread(target=thread_target, args = (thread_args))
    t.daemon = True
    t.start()
    processes.append(t)


# This function prints error and exits
def errorAndExit(exception_message):
    print "\nERROR - %s" %(exception_message)
    exit()


# This function changes the color of the prompt
def change_prompt_color(color):
    colors = {
        'red': "\033[1;31m",
        'green': "\033[0;32m",
        'normal': "\033[0;0m"
    }
    stdout.write(colors.get(color))


# This function prints a text in color and returns to normal
def print_in_color(color, msg):
    change_prompt_color(color)
    print msg
    change_prompt_color('normal')


# This function prints a group name surrounded with =
def print_header(text):
    text_len = len(text)
    print "\n" + ("=" * text_len)
    print text
    print ("=" * text_len)


# This function queries spotinst API endpoint and returns the result to a queue
def query_thread(queue, group, api_url, spotinst_token, req_method='GET', req_payload=None):
    try:
        headers = {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer %s' % spotinst_token,
        }
        if req_method == 'GET':
            result = get(api_url, headers=headers)
        elif req_method == 'PUT':
            result = put(api_url, headers=headers, data=req_payload)
        elif req_method == 'POST':
            result = post(api_url, headers=headers, data=req_payload)
        elif req_method == 'DELETE':
            result = delete(api_url, headers=headers, data=req_payload)
        queue.append([req_method, result, group])
    except Exception as e:
        errorAndExit(e.message)


# This function queries spotinst API endpoint
def query_api(api_url, spotinst_token, req_method='GET', req_payload=None):
    try:
        headers = {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer %s' % spotinst_token,
        }
        if req_method == 'GET':
            return get(api_url, headers=headers)
        elif req_method == 'PUT':
            return put(api_url, headers=headers, data=req_payload)
        elif req_method == 'POST':
            return post(api_url, headers=headers, data=req_payload)
        elif req_method == 'DELETE':
            return delete(api_url, headers=headers, data=req_payload)
    except Exception as e:
        errorAndExit(e.message)


# This function returns a groups dict, filtered by name (contains) or all if parameter is empty
def get_groups(grep_list, ungrep_list):
    print "\nQuerying spotinst API, hold on..."
    result  = query_api(base_api_path, token)
    if result.status_code > 299:
        errorAndExit("bad response from Spotinst!\n%s" % result.content)
    data = loads(result.content)
    groups_dict = {}
    all_groups = data['response']['items']
    for group in all_groups:
        # check if the spot_group_name parameter is not empty
        # is so, need to return only the groups that matches the search
        group_name = group['name'].lower()
        if [n for n in grep_list if n in group_name] and not [n for n in ungrep_list if n in group_name]:
            groups_dict[group['name']] = [group['id'], group['capacity']['minimum'], group['capacity']['target'], group['capacity']['maximum']]
    # sort the list by name
    sorted_inst = OrderedDict(sorted(groups_dict.items()))
    return sorted_inst


# This function prints groups as a table
def print_all_groups(groups_to_print):
    table = PrettyTable(['#' ,'Group name', 'ID', 'Min', 'Target', 'Max'])
    table.align = "l"
    table.border = True
    counter = 1
    for key, value in groups_to_print.iteritems():
        table.add_row([counter, key, value[0], value[1], value[2], value[3]])
        counter += 1
    print_message("Found the following groups: ")

    print table


# This function calculates the percentage change between two given numbers
def calc_percentage_change(old_val, new_val):
    percentage_change = 0
    try:
        if old_val != 0:
            percentage_change = ((int(new_val) - int(old_val)) / float(old_val)) * 100
        return abs(percentage_change)
    except Exception as e:
        return percent_alert_threshold


# This function checks for changes in the group target and alerts the user
def check_change_in_target(group_name, current_group_target, desired_group_target, alert_threshold):
    target_change = calc_percentage_change(current_group_target, desired_group_target)
    ans_change = "y"
    if int(target_change) >= alert_threshold and not options.skip_validation:
        print "{} target value is: {}, requested target is: {}.".format(group_name, current_group_target, desired_group_target)
        ans_change = raw_input("This represent a change of over 30%, are you sure you want to proceed? [y/n] ")
    return ans_change


# This function prints a message surrounded by #
def print_message(msg):
    all_lines = msg.splitlines()
    longest_line = 0
    for line in all_lines:
        if len(line.strip()) > longest_line:
            longest_line = len(line.strip())
    padding = 8
    print "\n" + ("-" * (longest_line + padding))
    for line in msg.splitlines():
        print (" " * (padding / 2)) + line
    print ("-" * (longest_line + padding)) + "\n"


# This function makes sure the user wants to process with his choice
def user_make_sure(question):
    ans_from_user = raw_input(question)
    if ans_from_user !="y":
        print "\nExiting.."
        exit()


# function to get y or n from the user and return True/ False accordingly
def get_yes_no_from_user(question):
    ans_from_user = ""
    while ans_from_user != "y" and ans_from_user != "n":
        ans_from_user = raw_input(question)
        if ans_from_user != "y" and ans_from_user != "n":
            print "please answer 'y' or 'n' only!"
    if ans_from_user == "y":
        return True
    else:
        return False


# function to split parsed option to list by comma
def parser_split(option, opt, value, parser):
    setattr(parser.values, option.dest, value.split(','))


# function to validate pip packages
def validate_pip_packages():
    pip_version = getstatusoutput('pip -V')
    if pip_version[0] != 0:
        errorAndExit("python-pip is not installed, please install it before using this tool!\n"
                     "On MacOS, you can install it using one of the following:\n"
                     "'brew install python' or 'sudo easy_install pip")

    if 'python 2.7' not in pip_version[1]:
        errorAndExit("This script currently supports python 2.7 only!")

    installed_packages = [pkg.split('==')[0] for pkg in getoutput('pip freeze').split('\n')]
    required_packages = ['prettytable', 'requests']
    try:
        for pkg in required_packages:
            if pkg not in installed_packages:
                raise  DistributionNotFound
    except DistributionNotFound:
        errorAndExit("One of the required pip packages is not installed!\n"
                     "Please install all packages using the following command in the project's root folder:\n"
                     "pip install -r requirements.txt --user --upgrade")

##### MAIN ####
validate_pip_packages()
from prettytable import PrettyTable
from requests import put, get, post, delete

# define help and options
usage = "Usage: %prog [options]"
parser = OptionParser(usage)
parser.add_option("-g", "--grep", type="string", action="callback", dest="grep", callback=parser_split, default="", help="text to filter groups by")
parser.add_option("-d", "--get-data", action="store_true", dest="data", default="", help="get groups data")
parser.add_option("-s", "--get-status", action="store_true", dest="status", default="", help="get groups status")
parser.add_option("--suspension-status", action="store_true", dest="suspension", default="", help="get groups suspension status")
parser.add_option("-u", "--ungrep", type="string", action="callback", default="", callback=parser_split, dest="ungrep", help="text to exclude groups")
parser.add_option("-l", "--list", action="store_true", dest="list", help="show group list and exit")
parser.add_option("--min", action="store", dest="min", type=int, help="update group minimum capacity, must suuply with max and target")
parser.add_option("--target", action="store", dest="target", type=int, help="update group target capacity, must supply with min and max")
parser.add_option("--max", action="store", dest="max", type=int, help="update group maximum capacity, must supply with min and target")
parser.add_option("--scale-up", action="store", dest="scale_up", type=int, help="scale up group by X number of instances")
parser.add_option("--scale-down", action="store", dest="scale_down", type=int, help="scale down group by X number of instances")
parser.add_option("--suspend", action="store", choices=['AUTO_SCALE', 'AUTO_HEALING'], dest="suspend", help="suspend scaling or healing for a group")
parser.add_option("--unsuspend", action="store", dest="unsuspend", choices=['AUTO_SCALE', 'AUTO_HEALING'], help="unsuspend scaling or healing for a group")
parser.add_option("--roll", action="store_true", dest="roll", help="roll a group, must supply batch-size, and grace-period")
parser.add_option("--batch-size", action="store", dest="batch", type=int, help="roll batch size - must supply with the roll flag")
parser.add_option("--grace-period", action="store", dest="grace", type=int, help="roll grace period - must supply with the roll flag")
parser.add_option("--replace-ami", action="store", dest="ami", help="replace AMI for group")
parser.add_option("--replace-health", action="store", dest="health", choices=['EC2', 'ELB', "HCS"], help="replace health check type for a group")
parser.add_option("--user-data", action="store", dest="user_data", help="updated user data - supply a file path which contains the user data script (cloud init)")
parser.add_option("--detach-batch", action="store_true", dest="detach_batch", help="detach all instances for specific batch - choose from a list of batches")
parser.add_option("-y", "--skip-validation", action="store_true", dest="skip_validation", help="skip prompt validation for non-interactive mode")
(options, args) = parser.parse_args()

# show help as default and exit
if len(argv) == 1:
    system("python " + argv[0] + " -h")
    exit()

# global variables
percent_alert_threshold = 30
processes = []
requests_queue = []

# validate input
if options.max is not None and (options.min is None or options.target is None):
    errorAndExit("you must supply max with min and target!")
if options.min is not None and (options.max is None or options.target is None):
    errorAndExit("you must supply min with max and target!")
if options.target is not None and (options.max is None or options.min is None):
    errorAndExit("you must supply target with max and min!")
if options.roll is not None and (options.batch is None or options.grace is None):
    errorAndExit("you must supply batch size and grace period with the roll flag!")
if options.max is not None and options.min is not None and options.target is not None:
    if options.target < options.min or options.max < options.min or options.target > options.max:
        errorAndExit("check input - the number makes no sense!")

# set spotinst main path and check spotinst token
base_api_path = "https://api.spotinst.io/aws/ec2/group"
token = environ.get('spotinst_token')
if not token:
    errorAndExit("you must define an environment variable called 'spotinst_token' with a valid token (use export or .bashrc file)!")

# get all groups that matches the search
groups_to_update = get_groups(options.grep, options.ungrep)
if len(groups_to_update) == 0:
    errorAndExit("could not find any groups for the search term: {}".format(options.grep))
print_all_groups(groups_to_update)

# if the list flag was triggered, need to exit
if options.list is not None:
    exit()

# loop through each group and update
payload = None
user_validation = False
for group, group_values in groups_to_update.iteritems():
    group_id = group_values[0]

    # handle data request
    if options.data:
        req_type = 'GET'
        message = "retrieving data for group: {}".format(group)
        req_path = "{}/{}".format(base_api_path, group_id)

    # handle status request
    elif options.status:
        req_type = 'GET'
        message = "retrieving status for group: {}".format(group)
        req_path = "{}/{}/status".format(base_api_path, group_id)

    # handle suspension data request
    elif options.suspension:
        req_type = 'GET'
        message = "retrieving suspenstion status for group: {}".format(group)
        req_path = "{}/{}/suspension".format(base_api_path, group_id)

    # handle suspension request
    elif options.suspend is not None or options.unsuspend is not None:
        req_path = "{}/{}/suspension".format(base_api_path, group_id)

        if options.suspend is not None:
            req_type = 'POST'
            command = "suspend"
            payload = '{"processes":["%s"]}' % options.suspend
        elif options.unsuspend is not None:
            req_type = 'DELETE'
            command = "unsuspend"
            payload = '{"processes":["%s"]}' % options.unsuspend

        message = "sending request to {} the group".format(command)
    # handle scale request
    elif options.scale_down is not None or options.scale_up is not None:
        req_type = 'PUT'
        if options.scale_up is not None:
            command = "up"
            adjustment = options.scale_up
        elif options.scale_down is not None:
            command = "down"
            adjustment = options.scale_down
        # check that this change does not pass the percent_alert_threshold
        ans = check_change_in_target(group, group_values[2], int(adjustment) + int(group_values[2]), percent_alert_threshold)
        if ans != "y":
            print "\nSkipping update for this group..."
            continue
        req_path = "{}/{}/scale/{}\?adjustment={}".format(base_api_path, group_id, command, adjustment)
        message = "sending request to scale {} {} instances...".format(command, adjustment)

    # handle group update request
    elif options.min is not None and options.target is not None and options.max is not None:
        # check that this change does not pass the percent_alert_threshold
        change_ans = check_change_in_target(group, group_values[2], options.target, percent_alert_threshold)
        if change_ans != "y":
            print "\nSkipping update for this group..."
            continue
        payload = dumps({ "group": { "capacity": { "target": options.target, "minimum": options.min , "maximum": options.max }}})
        req_type = 'PUT'
        message = "sending the following payload: {}".format(payload)
        req_path = "{}/{}".format(base_api_path, group_id)

    # handle roll request
    elif options.roll is not None and options.batch is not None and options.grace is not None:
        req_type = 'PUT'
        req_path = "{}/{}/roll".format(base_api_path, group_id)
        payload = dumps({ "batchSizePercentage" : options.batch, "gracePeriod" : options.grace })
        message = "rolling group: {} with batch-size: {} and a grace period: {}".format(group, options.batch, options.grace)

    # handle replace ami
    elif options.ami is not None or options.health is not None:
        req_type = 'PUT'
        req_path = "{}/{}".format(base_api_path, group_id)
        if options.ami is not None:
            payload = dumps({ "group": { "compute": { "launchSpecification": { "imageId": options.ami  }}}})
            message = "replacing AMI for {}".format(group)
        else:
            payload = dumps({"group": {"compute": {"launchSpecification": {"healthCheckType": options.health}}}})
            message = "replacing health check type for {}".format(group)

    # handle replace of user data script
    elif options.user_data is not None:
        if not path.isfile(options.user_data):
            errorAndExit("{} is not a valid file name!".format(options.user_data))
        f = open(options.user_data, "r")
        user_data_script = f.read()
        f.close()
        user_data_script = b64encode(user_data_script)
        req_path = "{}/{}".format(base_api_path, group_id)
        req_type = 'PUT'
        payload = dumps({ "group": { "compute": { "launchSpecification": { "userData": user_data_script  }}}})
        message = "sending a request to update the user data script..."

    else:
        exit()

    # make sure the user wants to continue with the current filter (unless the req type is GET)
    if not user_validation and req_type != 'GET':
        if not options.skip_validation:
            user_make_sure("\nAre you sure you want to updated these groups [y/n]? ")
        else:
            print "Found skip validation option, skipping user prompt..."
        user_validation = True

    # send requests as threads
    try:
        print message
        open_thread(query_thread, (requests_queue, group, req_path, token, req_type, payload))
    except Exception as e:
        errorAndExit(e)

# wait for all threads to finish
for p in processes:
    p.join()

# print the results
for result in requests_queue:
    request_type = result[0]
    request_result = result[1]
    request_group = result[2]
    print_header(request_group)
    if request_result.status_code == 200:
        if request_type == 'GET':
            print request_result.content
        else:
            print_in_color('green', "Update was successful!")
    else:
        data = loads(request_result.content)
        print_in_color('red', "Error while updating group!\nstatus code: {}, reason: {}\n".format(request_result.status_code, data['response']['errors'][0]['message']))


print_message("Done running on all groups!")

